// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (
    user_id,
    amount,
    interest_rate,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, user_id, amount, status, interest_rate
`

type CreateLoanParams struct {
	UserID       pgtype.Int4    `json:"user_id"`
	Amount       pgtype.Numeric `json:"amount"`
	InterestRate pgtype.Numeric `json:"interest_rate"`
	Status       pgtype.Text    `json:"status"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.UserID,
		arg.Amount,
		arg.InterestRate,
		arg.Status,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.InterestRate,
	)
	return i, err
}

const deleteLoanByID = `-- name: DeleteLoanByID :exec
DELETE FROM loans
WHERE id = $1
`

func (q *Queries) DeleteLoanByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLoanByID, id)
	return err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, user_id, amount, status, interest_rate FROM loans
WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int32) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.InterestRate,
	)
	return i, err
}

const listAllLoans = `-- name: ListAllLoans :many
SELECT id, user_id, amount, status, interest_rate FROM loans
ORDER BY id
`

func (q *Queries) ListAllLoans(ctx context.Context) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listAllLoans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.InterestRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByUserID = `-- name: ListLoansByUserID :many
SELECT id, user_id, amount, status, interest_rate FROM loans
WHERE user_id = $1  
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListLoansByUserIDParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListLoansByUserID(ctx context.Context, arg ListLoansByUserIDParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loan{}
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.InterestRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoanStatus = `-- name: UpdateLoanStatus :one
UPDATE loans
SET status = $2
WHERE id = $1
RETURNING id, user_id, amount, status, interest_rate
`

type UpdateLoanStatusParams struct {
	ID     int32       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanStatus, arg.ID, arg.Status)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.InterestRate,
	)
	return i, err
}
