// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
RETURNING id, user_id, account_number, type, balance
`

type AddAccountBalanceParams struct {
	ID      int32          `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Type,
		&i.Balance,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id,
    account_number,
    type,
    balance
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, user_id, account_number, type, balance
`

type CreateAccountParams struct {
	UserID        pgtype.Int4    `json:"user_id"`
	AccountNumber pgtype.Text    `json:"account_number"`
	Type          pgtype.Text    `json:"type"`
	Balance       pgtype.Numeric `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.AccountNumber,
		arg.Type,
		arg.Balance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Type,
		&i.Balance,
	)
	return i, err
}

const deleteAccountByID = `-- name: DeleteAccountByID :exec
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccountByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccountByID, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, account_number, type, balance FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Type,
		&i.Balance,
	)
	return i, err
}

const listAccountsByUserID = `-- name: ListAccountsByUserID :many
SELECT id, user_id, account_number, type, balance FROM accounts
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListAccountsByUserID(ctx context.Context, userID pgtype.Int4) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Type,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2
WHERE id = $1
RETURNING id, user_id, account_number, type, balance
`

type UpdateAccountBalanceParams struct {
	ID      int32          `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Type,
		&i.Balance,
	)
	return i, err
}
