// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            int32          `json:"id"`
	UserID        pgtype.Int4    `json:"user_id"`
	AccountNumber pgtype.Text    `json:"account_number"`
	Type          pgtype.Text    `json:"type"`
	Balance       pgtype.Numeric `json:"balance"`
}

type Loan struct {
	ID           int32          `json:"id"`
	UserID       pgtype.Int4    `json:"user_id"`
	Amount       pgtype.Numeric `json:"amount"`
	Status       pgtype.Text    `json:"status"`
	InterestRate pgtype.Numeric `json:"interest_rate"`
}

type MutualFund struct {
	ID           int32          `json:"id"`
	UserID       pgtype.Int4    `json:"user_id"`
	FundName     pgtype.Text    `json:"fund_name"`
	UnitsHeld    pgtype.Numeric `json:"units_held"`
	CurrentValue pgtype.Numeric `json:"current_value"`
}

type Transaction struct {
	ID          int32            `json:"id"`
	AccountID   pgtype.Int4      `json:"account_id"`
	Amount      pgtype.Numeric   `json:"amount"`
	Type        pgtype.Text      `json:"type"`
	Description pgtype.Text      `json:"description"`
	Timestamp   pgtype.Timestamp `json:"timestamp"`
}

type User struct {
	ID           int32            `json:"id"`
	Username     pgtype.Text      `json:"username"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	FullName     pgtype.Text      `json:"full_name"`
	Email        pgtype.Text      `json:"email"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
