// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mutual_funds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMutualFund = `-- name: CreateMutualFund :one
INSERT INTO mutual_funds (
    user_id,
    fund_name,
    units_held,
    current_value
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, user_id, fund_name, units_held, current_value
`

type CreateMutualFundParams struct {
	UserID       pgtype.Int4    `json:"user_id"`
	FundName     pgtype.Text    `json:"fund_name"`
	UnitsHeld    pgtype.Numeric `json:"units_held"`
	CurrentValue pgtype.Numeric `json:"current_value"`
}

func (q *Queries) CreateMutualFund(ctx context.Context, arg CreateMutualFundParams) (MutualFund, error) {
	row := q.db.QueryRow(ctx, createMutualFund,
		arg.UserID,
		arg.FundName,
		arg.UnitsHeld,
		arg.CurrentValue,
	)
	var i MutualFund
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FundName,
		&i.UnitsHeld,
		&i.CurrentValue,
	)
	return i, err
}

const deleteMutualFundByID = `-- name: DeleteMutualFundByID :exec
DELETE FROM mutual_funds
WHERE id = $1
`

func (q *Queries) DeleteMutualFundByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMutualFundByID, id)
	return err
}

const getMutualFundByID = `-- name: GetMutualFundByID :one
SELECT id, user_id, fund_name, units_held, current_value FROM mutual_funds
WHERE id = $1
`

func (q *Queries) GetMutualFundByID(ctx context.Context, id int32) (MutualFund, error) {
	row := q.db.QueryRow(ctx, getMutualFundByID, id)
	var i MutualFund
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FundName,
		&i.UnitsHeld,
		&i.CurrentValue,
	)
	return i, err
}

const listMutualFunds = `-- name: ListMutualFunds :many
SELECT id, user_id, fund_name, units_held, current_value FROM mutual_funds
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListMutualFundsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMutualFunds(ctx context.Context, arg ListMutualFundsParams) ([]MutualFund, error) {
	rows, err := q.db.Query(ctx, listMutualFunds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MutualFund{}
	for rows.Next() {
		var i MutualFund
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FundName,
			&i.UnitsHeld,
			&i.CurrentValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualFundsByUserID = `-- name: ListMutualFundsByUserID :many
SELECT id, user_id, fund_name, units_held, current_value FROM mutual_funds
WHERE user_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListMutualFundsByUserIDParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListMutualFundsByUserID(ctx context.Context, arg ListMutualFundsByUserIDParams) ([]MutualFund, error) {
	rows, err := q.db.Query(ctx, listMutualFundsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MutualFund{}
	for rows.Next() {
		var i MutualFund
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FundName,
			&i.UnitsHeld,
			&i.CurrentValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMutualFundValue = `-- name: UpdateMutualFundValue :one
UPDATE mutual_funds
SET current_value = $2
WHERE id = $1
RETURNING id, user_id, fund_name, units_held, current_value
`

type UpdateMutualFundValueParams struct {
	ID           int32          `json:"id"`
	CurrentValue pgtype.Numeric `json:"current_value"`
}

func (q *Queries) UpdateMutualFundValue(ctx context.Context, arg UpdateMutualFundValueParams) (MutualFund, error) {
	row := q.db.QueryRow(ctx, updateMutualFundValue, arg.ID, arg.CurrentValue)
	var i MutualFund
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FundName,
		&i.UnitsHeld,
		&i.CurrentValue,
	)
	return i, err
}
