// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateMutualFund(ctx context.Context, arg CreateMutualFundParams) (MutualFund, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountByID(ctx context.Context, id int32) error
	DeleteLoanByID(ctx context.Context, id int32) error
	DeleteMutualFundByID(ctx context.Context, id int32) error
	DeleteTransactionByID(ctx context.Context, id int32) error
	DeleteUserByID(ctx context.Context, id int32) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetLoanByID(ctx context.Context, id int32) (Loan, error)
	GetMutualFundByID(ctx context.Context, id int32) (MutualFund, error)
	GetTransactionByID(ctx context.Context, id int32) (Transaction, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	ListAccountsByUserID(ctx context.Context, userID pgtype.Int4) ([]Account, error)
	ListAllLoans(ctx context.Context) ([]Loan, error)
	ListAllTransactions(ctx context.Context, arg ListAllTransactionsParams) ([]Transaction, error)
	ListLoansByUserID(ctx context.Context, arg ListLoansByUserIDParams) ([]Loan, error)
	ListMutualFunds(ctx context.Context, arg ListMutualFundsParams) ([]MutualFund, error)
	ListMutualFundsByUserID(ctx context.Context, arg ListMutualFundsByUserIDParams) ([]MutualFund, error)
	ListTransactionsByAccountID(ctx context.Context, arg ListTransactionsByAccountIDParams) ([]Transaction, error)
	ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]Transaction, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (Loan, error)
	UpdateMutualFundValue(ctx context.Context, arg UpdateMutualFundValueParams) (MutualFund, error)
}

var _ Querier = (*Queries)(nil)
