// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    account_id,
    amount,
    type,
    description,
    timestamp
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
) RETURNING id, account_id, amount, type, description, timestamp
`

type CreateTransactionParams struct {
	AccountID   pgtype.Int4    `json:"account_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Type        pgtype.Text    `json:"type"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.Amount,
		arg.Type,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.Timestamp,
	)
	return i, err
}

const deleteTransactionByID = `-- name: DeleteTransactionByID :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransactionByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTransactionByID, id)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, amount, type, description, timestamp FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.Timestamp,
	)
	return i, err
}

const listAllTransactions = `-- name: ListAllTransactions :many
SELECT id, account_id, amount, type, description, timestamp FROM transactions
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListAllTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllTransactions(ctx context.Context, arg ListAllTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listAllTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountID = `-- name: ListTransactionsByAccountID :many
SELECT id, account_id, amount, type, description, timestamp FROM transactions  
WHERE account_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAccountIDParams struct {
	AccountID pgtype.Int4 `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccountID(ctx context.Context, arg ListTransactionsByAccountIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT id, account_id, amount, type, description, timestamp FROM transactions
WHERE type = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByTypeParams struct {
	Type   pgtype.Text `json:"type"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
